package com.chaevsfe.valence.modules.woodworks;

import java.util.List;

// Generated by tools/gen_woodworks.py. Do not edit.
// Families absent from the running version's registry are skipped at registration.
public final class WoodworksTable
{
    public record Row (String name, String planksBlock, String logBlock, boolean stem) { }

    public static final List<Row> ROWS = List.of(
        new Row("oak", "minecraft:oak_planks", "minecraft:oak_log", false),
        new Row("spruce", "minecraft:spruce_planks", "minecraft:spruce_log", false),
        new Row("birch", "minecraft:birch_planks", "minecraft:birch_log", false),
        new Row("jungle", "minecraft:jungle_planks", "minecraft:jungle_log", false),
        new Row("acacia", "minecraft:acacia_planks", "minecraft:acacia_log", false),
        new Row("dark_oak", "minecraft:dark_oak_planks", "minecraft:dark_oak_log", false),
        new Row("mangrove", "minecraft:mangrove_planks", "minecraft:mangrove_log", false),
        new Row("cherry", "minecraft:cherry_planks", "minecraft:cherry_log", false),
        new Row("pale_oak", "minecraft:pale_oak_planks", "minecraft:pale_oak_log", false),
        new Row("crimson", "minecraft:crimson_planks", "minecraft:crimson_stem", true),
        new Row("warped", "minecraft:warped_planks", "minecraft:warped_stem", true),
        new Row("bamboo", "minecraft:bamboo_planks", null, false));

    private WoodworksTable () { }
}
